10 REM **** PROGRAMA ENTRADA MOL ****
20 REM Crea datos para el programa MOL3D
30 INPUT"INTRODUZCA NOMBRE DEL FICHERO";n$
40 OPENOUT n$
50 INPUT "NOMBRE DE LA MOLECULA";h$
60 PRINT #9,h$
70 INPUT"NUMERO DE ATOMOS";atomos
80 PRINT #9,atomos
90 FOR i=1 TO atomos
100 INPUT "INTRODUZCA LAS COORDENADAS X,Y,Z";x,y,z
105 INPUT "INTRODUZCA EL TAMAÑO DEL ATOMO";s
110 PRINT #9,x,y,z,s
120 NEXT i
130 CLOSEOUT
140 END:REM Sacabao
